name: Work Item (Tables)
description: 테이블(도메인) 단위 운영 작업 생성
title: "[Task] "
labels: []

body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: 작업의 비즈니스 임팩트/긴급도
      options: [Critical, High, Medium, Low]

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: 작업 테이블(대표 도메인) 1개를 선택하세요
      options:
        - comments
        - faqs
        - locations
        - members
        - notices
        - post_images
        - post_like
        - posts
        - store_categories
        - store_images
        - store_operating_hour
        - stores
        - verification

  - type: checkboxes
    id: affected_tables
    attributes:
      label: Affected Tables
      description: 함께 영향을 받는 테이블(복수 선택)
      options:
        - label: comments
        - label: faqs
        - label: locations
        - label: members
        - label: notices
        - label: post_images
        - label: post_like
        - label: posts
        - label: store_categories
        - label: store_images
        - label: store_operating_hour
        - label: stores
        - label: verification

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: 기술 영역
      options: [Frontend, Backend, DevOps, Data]

  - type: dropdown
    id: story_points
    attributes:
      label: Story Points
      description: 작업 규모/복잡도 (피보나치)
      options: ["1","2","3","4","5"]

#  - type: dropdown
#    id: due_year
#    attributes:
#      label: Due Year
#      options: ["2025","2026","2027"]
#
#  - type: dropdown
#    id: due_month
#    attributes:
#      label: Due Month
#      options: ["01","02","03","04","05","06","07","08","09","10","11","12"]
#
#  - type: dropdown
#    id: due_day
#    attributes:
#      label: Due Day
#      options:
#        ["01","02","03","04","05","06","07","08","09","10",
#         "11","12","13","14","15","16","17","18","19","20",
#         "21","22","23","24","25","26","27","28","29","30","31"]

  - type: input
    id: due_date
    attributes:
      label: Due Date
      description: YYYY-MM-DD 형식으로 입력
      placeholder: 2025-09-12
    validations:
      required: false

  - type: dropdown
    id: due_in
    attributes:
      label: Due In
      description: 선택 시 워크플로가 실제 날짜로 변환
      options: ["Today", "+1d", "+3d", "Next Monday", "+1w", "+2w", "+1m"]

  - type: dropdown
    id: review_status
    attributes:
      label: Review Status
      description: 코드/기획 리뷰 상태
      options: [Pending, In Review, Approved, Changes Requested]

  - type: textarea
    id: details
    attributes:
      label: Details
      description: 무엇/왜/어떻게 (재현 스텝, 로그/쿼리, 기대동작, 영향 범위 등)
      placeholder: 내용을 입력하세요
    validations:
      required: true
