name: Work Item (Tables)
description: 테이블(도메인) 단위 운영 작업 생성
title: "[Task] "
labels: []

body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: 작업의 비즈니스 임팩트/긴급도
      options: [Critical, High, Medium, Low]

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: 작업 테이블(대표 도메인) 1개를 선택하세요
      options:
        - comments
        - faqs
        - locations
        - members
        - notices
        - post_images
        - post_like
        - posts
        - store_categories
        - store_images
        - store_operating_hour
        - stores
        - verification

#  - type: checkboxes
#    id: affected_tables
#    attributes:
#      label: Affected Tables
#      description: 함께 영향을 받는 테이블(복수 선택)
#      options:
#        - label: comments
#        - label: faqs
#        - label: locations
#        - label: members
#        - label: notices
#        - label: post_images
#        - label: post_like
#        - label: posts
#        - label: store_categories
#        - label: store_images
#        - label: store_operating_hour
#        - label: stores
#        - label: verification

  - type: dropdown
    id: change_type
    attributes:
      label: Change Type
      description: 작업 성격
      options: ["feat","fix","refactor","docs","chore","perf","test","ci","build","revert"]
    #docs : 문서만 수정/chore : 유지보수/잡무(코드 로직 변화 없음)/perf : 성능 개선/test : 테스트 추가/수정/ci, build : 파이프라인/빌드 변경/revert : 변경 되돌리기
    validations:
      required: true

  - type: input
    id: due_date
    attributes:
      label: Due Date
      description: YYYY-MM-DD 형식으로 입력
      placeholder: "2025-09-12"
    validations:
      required: false

  - type: textarea
    id: details
    attributes:
      label: Details
      description: 무엇/왜/어떻게 (재현 스텝, 로그/쿼리, 기대동작, 영향 범위 등)
      placeholder: 내용을 입력하세요
    validations:
      required: true
