name: Work item (Tables)
description: 테이블(도메인) 단위 운영 작업 생성
title: "[Task] "
labels: []

body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: [Critical, High, Medium, Low]
      default: 1   # 기본 High

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: 담당 테이블(대표 도메인) 1개를 선택하세요
      options:
        - comments
        - faqs
        - locations
        - members
        - notices
        - post_images
        - post_like
        - posts
        - store_categories
        - store_images
        - store_operating_hour
        - stores
        - verification

  - type: checkboxes
    id: affected_tables
    attributes:
      label: Affected Tables
      description: 영향 받는 테이블을 모두 선택하세요 (복수 선택)
      options:
        - label: comments
        - label: faqs
        - label: locations
        - label: members
        - label: notices
        - label: post_images
        - label: post_like
        - label: posts
        - label: store_categories
        - label: store_images
        - label: store_operating_hour
        - label: stores
        - label: verification

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: 기술 영역을 선택하세요
      options: [Frontend, Backend, DevOps, Data, QA]
      default: 0

  - type: dropdown
    id: story_points
    attributes:
      label: Story Points
      options: ["1","2","3","5","8","13"]
      default: 2

  - type: dropdown
    id: due_year
    attributes:
      label: Due Year
      options: ["2025","2026","2027","2028"]
      default: 0

  - type: dropdown
    id: due_month
    attributes:
      label: Due Month
      options: ["01","02","03","04","05","06","07","08","09","10","11","12"]

  - type: dropdown
    id: due_day
    attributes:
      label: Due Day
      options:
        ["01","02","03","04","05","06","07","08","09","10",
         "11","12","13","14","15","16","17","18","19","20",
         "21","22","23","24","25","26","27","28","29","30","31"]

  - type: dropdown
    id: review_status
    attributes:
      label: Review Status
    options: ["Pending","In Review","Approved","Changes Requested"]

  - type: textarea
    id: details
    attributes:
      label: Details
      description: 무엇을/왜/어떻게 (해당 테이블 기준으로 구체적으로)
      placeholder: 예) 스키마/인덱스/쿼리/재현 스텝/기대동작
    validations:
      required: true
