name: Work item
description: 프로젝트 작업 생성 (라벨 없이 필드로 관리)
title: "[Task] "
labels: []
body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: [Critical, High, Medium, Low]
      default: 2
  - type: dropdown
    id: component
    attributes:
      label: Component
      options: [Frontend, Backend, Database, DevOps]
  - type: input
    id: story_points
    attributes:
      label: Story Points
      placeholder: "예: 3"
  - type: input
    id: due_date
    attributes:
      label: Due Date (YYYY-MM-DD)
      placeholder: "예: 2025-09-15"
  - type: textarea
    id: details
    attributes:
      label: Details
      description: 무엇을/왜/어떻게
      placeholder: 내용을 입력하세요
    validations:
      required: true
