name: Work item
description: 프로젝트 작업 생성 (라벨 없이 필드로 관리)
title: "[Task] "
labels: []
body:
  - type: single_select
    id: priority
    attributes:
      label: Priority
      options: [🔴 Critical, 🟠 High, 🟡 Medium, 🟢 Low]
      default: 2
  - type: single_select
    id: component
    attributes:
      label: Component
      options: [Frontend, Backend, Database, DevOps]
  - type: input
    id: story_points
    attributes:
      label: Story Points
      placeholder: "예: 3"
  - type: dropdown
    id: due_year
    attributes:
      label: Due Year
      options: ["2025","2026","2027"]
      default: 0
  - type: dropdown
    id: due_month
    attributes:
      label: Due Month
      options: ["01","02","03","04","05","06","07","08","09","10","11","12"]
  - type: dropdown
    id: due_day
    attributes:
      label: Due Day
      options: ["01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31"]
  - type: textarea
    id: details
    attributes:
      label: Details
      description: 무엇을/왜/어떻게
      placeholder: 내용을 입력하세요
    validations:
      required: true
