name: Deploy Docker Image to Docker Hub

on:
  workflow_run:
    workflows: ["Run Tests (CI)"]
    types:
      - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: build/libs/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Git metadata
        id: vars
        run: |
          echo "SHA_TAG=sha-$(git rev-parse --short ${{ github.event.workflow_run.head_sha }})" >> $GITHUB_ENV
          echo "DATE_TAG=build-$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            pinup0106/pinup:latest
            pinup0106/pinup:${{ env.SHA_TAG }}
            pinup0106/pinup:${{ env.DATE_TAG }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull pinup0106/pinup:latest
            docker stop pinup-container || true
            docker rm pinup-container || true
            docker run -d --name pinup-container -p 80:8080 pinup0106/pinup:latest
